### ISSUE TITLE
RuntimeException: Selecting an audio file

### ISSUE THREAD

**Issue by ebsuku** [2find/stereo#36]
Hi There

After selecting an audio file the app crashes

The code I'm using is
```
Future<Null> _selectAudio(BuildContext context) async {
    print("Selecting audio");
    try {
      var track = await _stereo.picker();  
      File newFile = File(track.path);
      print(newFile.length());
    } catch (e) {
      print(e);
    }
  }
```

The exception is 

```
Shutting down VM
FATAL EXCEPTION: main
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/3430-6463:Android/output/Afrik.mp3 flg=0x1 }} to activity {com.example.mobile/com.example.mobile.MainActivity}: java.lang.IllegalArgumentException
E/AndroidRuntime(18479): at android.app.ActivityThread.deliverResults(ActivityThread.java:3742)
E/AndroidRuntime(18479): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3785)
E/AndroidRuntime(18479): 	at android.app.ActivityThread.access$1400(ActivityThread.java:157)
E/AndroidRuntime(18479): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
E/AndroidRuntime(18479): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18479): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(18479): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
E/AndroidRuntime(18479): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18479): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
E/AndroidRuntime(18479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
E/AndroidRuntime(18479): Caused by: java.lang.IllegalArgumentException
E/AndroidRuntime(18479): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:73)
E/AndroidRuntime(18479): 	at com.twofind.stereo.AudioTrack.toJson(AudioTrack.java:14)
E/AndroidRuntime(18479): 	at com.twofind.stereo.StereoPlugin.onActivityResult(StereoPlugin.java:242)
E/AndroidRuntime(18479): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime(18479): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:146)
E/AndroidRuntime(18479): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:139)
E/AndroidRuntime(18479): 	at android.app.Activity.dispatchActivityResult(Activity.java:6463)
E/AndroidRuntime(18479): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
```
The audio file I'm selecting is in external storage, I moved it to internal and still got the same error.

**Comment by ebsuku** [comment]
The upgrade of flutter seems to have fixed this.

**Comment by faku99** [comment]
Thanks a lot for handling the issue. I'm really sorry that I didn't have the time to help you with it. Glad the update fixed the issue.
